#!/bin/bash
#qemu-system-x86_64                  \
	#-m 8G                           \
	#-cpu qemu64,+ssse3,+sse4.1,+sse4.2,+x2apic                   \
	#--enable-kvm                    \
	#-net user,hostfwd=tcp::2222-:4242 \
	#-net nic
	#-hda "/home/jbettini/sgoinfre/debian.iso"

qemu-system-x86_64 \
	-m 8G \
	-smp 4 \
    -monitor stdio \
    -cpu host \
	-net user,hostfwd=tcp::2222-:4242 \
	-net nic \
	-enable-kvm \
    -device qemu-xhci \
	-hda -hda ./override.iso
